version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - 4000:4000
    env_file: ./backend/.env
    networks:
      - backend
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - 8080:80
    networks:
      - frontend

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file: ./backend/.env
    restart: always
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  postgres_data:
